/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectotiendavehiculos;

import javax.swing.JOptionPane;

/**
 *
 * @author Universidad
 */
public class RegistroCliente extends javax.swing.JFrame {

    /**
     * Creates new form RegistroCliente
     */
    public RegistroCliente() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PRegistroCliente = new javax.swing.JPanel();
        TFNombre = new javax.swing.JTextField();
        TFSegundoApellido = new javax.swing.JTextField();
        TFPrimerApellido = new javax.swing.JTextField();
        TFNumero = new javax.swing.JTextField();
        TFCorreo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TADireccion = new javax.swing.JTextArea();
        LPrimerApellido = new javax.swing.JLabel();
        LNombre = new javax.swing.JLabel();
        LTelefono = new javax.swing.JLabel();
        LSegundoApellido = new javax.swing.JLabel();
        LCorreo = new javax.swing.JLabel();
        BtnRegistrar = new javax.swing.JToggleButton();
        LDireccion = new javax.swing.JLabel();
        BtnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PRegistroCliente.setBackground(new java.awt.Color(51, 51, 51));

        TFNombre.setBackground(new java.awt.Color(102, 102, 102));
        TFNombre.setForeground(new java.awt.Color(255, 255, 255));

        TFSegundoApellido.setBackground(new java.awt.Color(102, 102, 102));
        TFSegundoApellido.setForeground(new java.awt.Color(255, 255, 255));

        TFPrimerApellido.setBackground(new java.awt.Color(102, 102, 102));
        TFPrimerApellido.setForeground(new java.awt.Color(255, 255, 255));
        TFPrimerApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFPrimerApellidoActionPerformed(evt);
            }
        });

        TFNumero.setBackground(new java.awt.Color(102, 102, 102));
        TFNumero.setForeground(new java.awt.Color(255, 255, 255));

        TFCorreo.setBackground(new java.awt.Color(102, 102, 102));
        TFCorreo.setForeground(new java.awt.Color(255, 255, 255));

        TADireccion.setBackground(new java.awt.Color(102, 102, 102));
        TADireccion.setColumns(20);
        TADireccion.setForeground(new java.awt.Color(255, 255, 255));
        TADireccion.setRows(5);
        jScrollPane1.setViewportView(TADireccion);

        LPrimerApellido.setForeground(new java.awt.Color(204, 204, 204));
        LPrimerApellido.setText("Primer Apellido");

        LNombre.setForeground(new java.awt.Color(204, 204, 204));
        LNombre.setText("Nombre");

        LTelefono.setForeground(new java.awt.Color(204, 204, 204));
        LTelefono.setText("Número de Teléfono");

        LSegundoApellido.setForeground(new java.awt.Color(204, 204, 204));
        LSegundoApellido.setText("Segundo Apellido");

        LCorreo.setForeground(new java.awt.Color(204, 204, 204));
        LCorreo.setText("Correo Electrónico");

        BtnRegistrar.setText("Registrar Cliente");
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });

        LDireccion.setForeground(new java.awt.Color(204, 204, 204));
        LDireccion.setText("Dirección");

        BtnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectotiendavehiculos/Home.png"))); // NOI18N
        BtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PRegistroClienteLayout = new javax.swing.GroupLayout(PRegistroCliente);
        PRegistroCliente.setLayout(PRegistroClienteLayout);
        PRegistroClienteLayout.setHorizontalGroup(
            PRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PRegistroClienteLayout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(BtnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addGap(321, 321, 321))
            .addGroup(PRegistroClienteLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(PRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PRegistroClienteLayout.createSequentialGroup()
                        .addComponent(LDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PRegistroClienteLayout.createSequentialGroup()
                        .addGroup(PRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(PRegistroClienteLayout.createSequentialGroup()
                                .addGroup(PRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PRegistroClienteLayout.createSequentialGroup()
                                        .addComponent(LCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PRegistroClienteLayout.createSequentialGroup()
                                        .addComponent(LNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PRegistroClienteLayout.createSequentialGroup()
                                        .addComponent(TFCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PRegistroClienteLayout.createSequentialGroup()
                                        .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TFPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(65, 65, 65)
                                .addGroup(PRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(143, 143, 143))))
            .addGroup(PRegistroClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnHome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PRegistroClienteLayout.setVerticalGroup(
            PRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PRegistroClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(PRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(LDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PRegistroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PRegistroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        Clientes cliente = new Clientes();
        if (TFNombre.getText() == "") {
            JOptionPane.showMessageDialog(null, "Nel");
        } else {
            cliente.setNombre(TFNombre.getText());
            cliente.setApellido1(TFPrimerApellido.getText());
            cliente.setApellido2(TFSegundoApellido.getText());
            cliente.setEmail(TFCorreo.getText());
            cliente.setTelefono(Integer.parseInt(TFNumero.getText()));
            cliente.setDireccion(TADireccion.getText());

            JOptionPane.showMessageDialog(null, "Se Registró el Cliente: " + cliente.getNombre() + " " + cliente.getApellido1() + " " + cliente.getApellido2());
            dispose();
            CatalogoVehiculos vehiculo = new CatalogoVehiculos();
            vehiculo.setVisible(true);
        }

    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void TFPrimerApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFPrimerApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFPrimerApellidoActionPerformed

    private void BtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHomeActionPerformed
        dispose();
        Tienda home = new Tienda();
        home.setVisible(true);
    }//GEN-LAST:event_BtnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHome;
    private javax.swing.JToggleButton BtnRegistrar;
    private javax.swing.JLabel LCorreo;
    private javax.swing.JLabel LDireccion;
    private javax.swing.JLabel LNombre;
    private javax.swing.JLabel LPrimerApellido;
    private javax.swing.JLabel LSegundoApellido;
    private javax.swing.JLabel LTelefono;
    private javax.swing.JPanel PRegistroCliente;
    private javax.swing.JTextArea TADireccion;
    private javax.swing.JTextField TFCorreo;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JTextField TFNumero;
    private javax.swing.JTextField TFPrimerApellido;
    private javax.swing.JTextField TFSegundoApellido;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
